(require 'run-assoc)
(setq associated-program-alist
      '(("gnochm" "\\.chm$")
	("xpdf" "\\.pdf$")
	("mplayer" "\\.mp3$")
	("mplayer" "\\.ogg$")
	("mplayer" "\\.avi$")
	("vlc" "\\.wmv$")
	("vlc" "\\.wkv$")
	("vlc" "\\.mov$")
	("mplayer" "\\.flv$")
	("evince" "\\.ps$")
	("djview" "\\.djvu$")
	((lambda (file)
	   (browse-url (concat "file:///" (expand-file-name file)))) "\\.html?$")))
